### ISSUE TITLE
[Bug]: initial-buffer-choice is not reset after startup

### ISSUE THREAD

**Issue by leotaku** [progfolio/elpaca#49]
### Emacs Version

GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)

### Operating System

Linux

### Bug Description

When processing queues, elpaca will set `initial-buffer-choice` to a function for displaying the log buffer. The value is never reset, so frames created using e.g. `emacsclient -c` will always show the elpaca status buffer.

**Comment by progfolio** [comment]
Thank you for the report.
I've pushed a fix which should do the trick. 
You can update Elpaca via the `elpaca-update` command followed by  the `restart-emacs` command.
Testing is appreciated.

**Comment by leotaku** [comment]
Thanks for the quick fix. Unfortunately, I still experience the problem under specific circumstances: When I run a command like `elpaca-update-all` in a running Emacs session, `initial-buffer-choice` will be set. However, while I am shown the elpaca log buffer, the `initial-buffer-choice` function is not run until I create a new frame, meaning `initial-buffer-choice` is not yet reset and the next frame I create also shows the elpaca log buffer.

**Comment by progfolio** [comment]
> I would also add a check to resetting initial-buffer-choice to elpaca--initial-buffer-choice only when initial-buffer-choice is equal to 'elpaca--set-initial-buffer. That way, we don't accidentally override some users customization.

I had a guard like that in an earlier version of the patch, but I thought I could get away without it:
https://github.com/progfolio/elpaca/commit/b00361c35c4fd9804e9a8b30fce31d26d5e581bb
Your suggestion makes sense, though. I've added the guard back in.

Now the initial-buffer-choice should only be set while reading the init-file.
That should prevent the issue cropping up after when a build a command is issued.
`elpaca-update` will fail because I've force pushed to the  master branch.
You should be able to `rm -rf elpaca/builds/elpaca/ elpaca/repos/elpaca/` and `restart-emacs` to get the latest version installed.

Let me know how if this version solves the issue.

**Comment by leotaku** [comment]
The new version fixes the issue for me, thanks a lot!

**Comment by progfolio** [comment]
Glad it worked for you.
Thank you for testing.

**Comment by wrycode** [comment]
Still experiencing this issue in Emacs 29.4

**Comment by progfolio** [comment]
> Still experiencing this issue in Emacs 29.4

Please fill out a separate issue form with the requested info.
